# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79890c95ebf84db752f251f32047d5f90121f58f0dcfb2ea1df603ed36df1796c56eb8c85bb028b41ff548a6841ef05f5579418c5416503cb7106cb2b2a1e1c5

test:
  secret_key_base: 619e1d2ed51c62ab4502842292fcc97fde7a4bcd9aaa1f9ed417fcb226eb206f58b4a79deaeef522b07a8c42b495a7b96bc5c05683c995351c88f6cfd435c96e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
